### ISSUE TITLE
Problem with api under lollipop

### ISSUE THREAD

**Issue by mmahamed** [mutualmobile/CardStackUI#7]
Hi
Thanks for your great library.
Everything is good but I get android.view.InflateException on api under Lollipop
I don't know the source of error.
Could you please save me!

PS : your demo app also has this problem.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ir.marmarsefid.clean/ir.marmarsefid.clean.activity.TestCardStack}: android.view.InflateException: Binary XML file line #5: Error inflating class com.mutualmobile.cardstack.CardStackLayout
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                        at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: android.view.InflateException: Binary XML file line #5: Error inflating class com.mutualmobile.cardstack.CardStackLayout
```
Thanks in advance

**Comment by tushar-acharya** [comment]
@mmahamed On it :+1:

**Comment by tushar-acharya** [comment]
@mmahamed Just pushed out a fix. Let me know if it's working for you so that I can close this issue.

**Comment by mmahamed** [comment]
dear @tushar-acharya 
Thanks a lot because of your speed and attention.
I tested your changes and worked great in 'Genymotion Samsung galaxy s5 with android 4.4.4 emulator' and 'Samsung galaxy tab 7.0 plus with android 4.1.2 real device'
God bless you.

**Comment by mmahamed** [comment]
And Please update maven repositories so we can get new version via gradle.
Thanks again

**Comment by tushar-acharya** [comment]
@mmahamed Done :+1: Thanks for notifying about the issue
